export default [
    {
        task_id: 1,
        assignee: [],
        assigner: "",
        taskName: "Ultrakey HRMS",
        description: "Create HRMS App for Ulytrakey IT Solutions.",
        deadline: "2024-11-20T09:00:00.000Z",
        createdAt: "2024-09-10T15:30:00.000Z",
        underProject: { projectName: "", project_id: null },
        status: "New",
    },
    {
        task_id: 2,
        assignee: [],
        assigner: "",
        taskName: "Trending News Guru App",
        description:
            "Create Trending News Guru App for Ulytrakey IT Solutions. Hello, I hope you are doing good. Also, Owrk on Website with Java Backend and JavaScript on Frontend Create Trending News Guru App for Ulytrakey IT Solutions. Frontend Create Trending News Guru App for Ulytrakey IT Solutions. Create Trending News Guru App for Ulytrakey IT Solutions.",
        deadline: "2024-10-15T12:45:00.000Z",
        createdAt: "2024-09-13T09:00:00.000Z",
        underProject: { projectName: "", project_id: null },
        status: "Completed",
    },
    {
        task_id: 3,
        assignee: [],
        assigner: "",
        taskName: "Ulytrakey CRM",
        description: "Create CRM for Ulytrakey IT Solutions.",
        deadline: "2024-09-30T18:00:00.000Z",
        createdAt: "2024-10-05T08:15:00.000Z",
        underProject: { projectName: "", project_id: null },
        status: "Overdue",
    },
]